arb-dir: lib/l10n
template-arb-file: app_en.arb
template-arb-file-zh: app_zh.arb
template-arb-file-zh-Hans: app_zh-Hans.arb
template-arb-file-zh-Hant-TW: app_zh-Hant-TW.arb
template-arb-file-zh-Hant-HK: app_zh-Hant-HK.arb
output-localization-file: app_localizations.dart
output-dir: lib/generated/l10n
